blog-post-unitary
netket/netket.org pull request #4
Opened 2022-05-30 21:13 UTC by PhilipVinc

cc @femtobit looks good for you?

2022-05-30 21:20 UTC, PhilipVinc commented
https://6295348d9779770008c9d407--brave-noether-a3f1b4.netlify.app/posts/3-unitaryhack/

2022-05-31 09:09 UTC, femtobit requested changes

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +NetKet is partecipating in the 2022 edition of [UnitaryHack](https://unitaryhack.dev), kindly sponsored by the quantum non-profit [Unitary Fund](https://unitary.fund).
```suggestion
NetKet is participating in the 2022 edition of [UnitaryHack](https://unitaryhack.dev), kindly sponsored by the quantum non-profit [Unitary Fund](https://unitary.fund).
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +The hackathon will run for two weeks, from Friday, June 3rd to Friday, June 17, and sees several high-profile quantum software projects proposing bounties to complete some tasks that will benefit the
```suggestion
The hackathon will run for two weeks, from Friday, June 3 to Friday, June 17. During the hackathon, several high-profile quantum software projects are each proposing several tasks for which Unitary Fund will provide a bounty to the participant completing the task.
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +The hackathon will run for two weeks, from Friday, June 3rd to Friday, June 17, and sees several high-profile quantum software projects proposing bounties to complete some tasks that will benefit the
Duplicate sentence.
```suggestion
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +NetKet is partecipating with 4 bounties to this Hackathon worth 300$ in total. To claim a bounty you need to get a PR accepted (not necessarily merged) by the maintainers *before* the end of the hack
```suggestion
NetKet is participating with 4 bounties to this hackathon, which are worth US$ 300 in total. To claim a bounty, you need to get a PR accepted (not necessarily merged) by the maintainers *before* the end of the hackathon. The precise instructions to follow are found in the [UnitaryHack](https://unitaryhack.dev/hacker-guide/) website and the list of bounties can be found [here](https://unitaryhack.dev/projects/netket/).
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +We are offering 4 bounties, some of which don't require particular experience with quantum physics but which will benefit the NetKet project as a whole. Here is the list:
```suggestion
We are offering the following 4 bounties, some of which don't require particular experience with quantum physics but which will benefit the usability of the NetKet project as a whole:
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +  [HDF5](https://docs.h5py.org) is a commonly used file-format that can store any kind of data. We would like contributors to implement a logger that can output this kind of files. No experience with
```suggestion
  [HDF5](https://docs.h5py.org) is a commonly used file-format that can store any kind of data. We would like contributors to implement a logger that can output this kind of files. No experience with quantum-related topics is required to win this bounty!
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +- [#1200](https://github.com/netket/netket/issues/1200) Add support for a single-file HDF5 based logging sink (75$)
```suggestion
- [#1200](https://github.com/netket/netket/issues/1200) Add support for a single-file HDF5 based logging sink ($75)
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +- [#1201](https://github.com/netket/netket/issues/1201) Use colors to signal bad sampling in expectation value/samplers state (50$)
```suggestion
- [#1201](https://github.com/netket/netket/issues/1201) Use colors to signal bad sampling in expectation value/samplers state ($50) 
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +  NetKet implements several kind of specialized types of operators which behave somewhat like a sparse matrix, but can encode operators in hilbert spaces much larger than 2^64, and which are much mor
```suggestion
- [#1206](https://github.com/netket/netket/issues/1206) Implement support for Ladder operators in PauliStrings ($100) 

  NetKet implements several kind of specialized types of operators which behave somewhat like a sparse matrix, but can encode operators in Hilbert spaces much larger than 2^64, and which are much more efficient at the operations that we require for Monte-Carlo algorithms. One of those operators is the `PauliStrings` operator, very similar to qiskit's and Pennylane's `PauliStringSum` operators. Right now it supports the "X,Y,Z,I" operators, but we would like to add support for ladder operators. To work on this task, you'll need some knowledge of linear algebra/elementary quantum mechanics.
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +  The algorithms used by NetKet to compute statistical estimators and convergence indicators require that the whole set of random variables be kept in memory. However, in the future we would like to
```suggestion
- [#1220](https://github.com/netket/netket/issues/1220) Add single-pass online statistics support to NetKet ($75) 

  The algorithms used by NetKet to compute statistical estimators and convergence indicators require that the whole set of random variables be kept in memory. However, in the future we would like to estimate those observables on amounts of data so large that do not fit on the memory of the device. Therefore, this bounty is about implementing single-pass algorithms that can estimate relevant quantities by reading the data only once. To work on this bounty, you'll need a basic understanding of statistics. 
```

2022-05-31 09:09 UTC, femtobit commented on content/posts/3-unitaryhack/index.md
> +If you are interested in those projects, but are unsure of where to start from, do get in touch with us through the [NetKet's Slack channel](https://join.slack.com/t/mlquantum/shared_invite/zt-19wibm
```suggestion
If you are interested in those projects, but are unsure of where to start from, do get in touch with us through [NetKet's Slack channel](https://join.slack.com/t/mlquantum/shared_invite/zt-19wibmfdv-LLRI6i43wrLev6oQX0OfOw) or by launching a discussion on GitHub. 
```

2022-05-31 11:40 UTC, merged